### ISSUE TITLE
Topaz Earrings ⭐⭐⭐

### ISSUE THREAD

**Issue by ChucklesTheBeard** [McRadane/totk-upgrade#12]
Topaz Earrings 3 star upgrade costs 6 topaz and 1 star fragment (in TOTK version 1.1.2 anyway)

Current version shows 20 rushrooms
![image](https://github.com/McRadane/totk-upgrade/assets/12536545/9ecb234d-f016-4fdb-90a7-843de5cda5c9)

---

Thanks for making this tool, and a special thanks for adding sorting by game order!

**Comment by Leomaradan** [comment]
Hi, thank you for your input, it will be changed in a couple of minutes :) #13

**Comment by Leomaradan** [comment]
Fixed
